import Foundation

extension String {
    // MARK: USED TEXTS
    
    // MARK: HOMEPAGE
    static var APP_NAME: String { return "APP_NAME".localised() }
    static var CALL_EMERGENCY: String { return "CALL_EMERGENCY".localised() }
    static var CALL_EMERGENCY_INFO: String { return "CALL_EMERGENCY_INFO".localised() }
    static var STATUS: String { return "STATUS".localised() }
    static var YOU_ARE_OFF_DUTY: String { return "YOU_ARE_OFF_DUTY".localised() }
    static var DEACTIVATE_CALL_ENTRY: String { return "DEACTIVATE_CALL_ENTRY".localised() }
    static var DEACTIVATE_CALL_ENTRY_INFO: String { return "DEACTIVATE_CALL_ENTRY_INFO".localised() }
    static var ACTIVE_USER: String { return "ACTIVE_USER".localised() }
    static var INACTIVE_USER: String { return "INACTIVE_USER".localised() }
    static var PROFILE_INCOMPLETE: String { return "PROFILE_INCOMPLETE".localised() }
    static var REGISTER: String { return "REGISTER".localised() }
    static var UNREGISTERED_USER: String { return "UNREGISTERED_USER".localised() }
    static var GO_TO_PROFILE: String { return "GO_TO_PROFILE".localised() }
    static var REPORT_PENDING_TO_COMPLETE: String { return "REPORT_PENDING_TO_COMPLETE".localised() }
    static var REPORTS_PENDING_TO_COMPLETE: String { return "REPORTS_PENDING_TO_COMPLETE".localised() }
    // MARK: SIDEMENU
    static var HOME_PAGE: String { return "HOME_PAGE".localised() }
    static var MAP: String { return "MAP".localised() }
    static var NEWS: String { return "NEWS".localised() }
    static var EVENTS: String { return "EVENTS".localised() }
    static var COURSES: String { return "COURSES".localised() }
    static var PROFILE: String { return "PROFILE".localised() }
    static var SETTINGS: String { return "SETTINGS".localised() }
    static var STANDBY_MODE: String { return "STANDBY_MODE".localised() }
    static var ACCOUNT: String { return "ACCOUNT".localised() }
    static var FAQ: String { return "FAQ".localised() }
    static var CONTACT: String { return "CONTACT".localised() }
    static var IMPRINT: String { return "IMPRINT".localised() }
    static var ABOUT_THE_APP: String { return "ABOUT_THE_APP".localised() }
    static var LEGAL_NOTICE: String { return "LEGAL_NOTICE".localised() }
    static var ACTIVE: String { return "ACTIVE".localised() }
    static var INACTIVE: String { return "INACTIVE".localised() }
    static var PAUSED: String { return "PAUSED".localised() }
    static var UNREGISTERED: String { return "UNREGISTERED".localised() }
    static var INCOMPLETE_PROFILE: String { return "INCOMPLETE_PROFILE".localised() }
    // MARK: PROFILE MENU
    static var AGREEMENT: String { return "AGREEMENT".localised() }
    static var SIGNED: String { return "SIGNED".localised() }
    static var NOT_SIGNED: String { return "NOT_SIGNED".localised() }
    static var PERSONAL_DATA: String { return "PERSONAL_DATA".localised() }
    static var COMPLETED: String { return "COMPLETED".localised() }
    static var NOT_COMPLETED: String { return "NOT_COMPLETED".localised() }
    static var FIRST_RESPONDER_CERTIFICATION: String { return "FIRST_RESPONDER_CERTIFICATION".localised() }
    static var NOT_ADDED: String { return "NOT_ADDED".localised() }
    static var ADDED: String { return "ADDED".localised() }
    static var ACCESS: String { return "ACCESS".localised() }
    static var LOCATION: String { return "LOCATION".localised() }
    static var NOTIFICATIONS: String { return "NOTIFICATIONS".localised() }
    static var AUTHORIZED: String { return "AUTHORIZED".localised() }
    static var NOT_AUTHORIZED: String { return "NOT_AUTHORIZED".localised() }
    // MARK: PROFILE CONTRACT
    static var DECLARATION: String { return "DECLARATION".localised() }
    static var DECLARATION_NOT_LOADED: String { return "DECLARATION_NOT_LOADED".localised() }
    static var DECLARATION_LOADING: String { return "DECLARATION_LOADING".localised() }
    static var AGREEMENT_INFO: String { return "AGREEMENT_INFO".localised() }
    static var SAVE_AND_SEND: String { return "SAVE_AND_SEND".localised() }
    static var AGREEMENT_FINAL_TEXT: String { return "AGREEMENT_FINAL_TEXT".localised() }
    static var AGREEMENT_DESCRIPTION_TEXT: String { return "AGREEMENT_DESCRIPTION_TEXT".localised() }
    static var AGREEMENT_DETAIL_TEXT: String { return "AGREEMENT_DETAIL_TEXT".localised() }
    static var SIGNED_ON: String { return "SIGNED_ON".localised() }
    static var CLEAR_SIGNATURE: String { return "CLEAR_SIGNATURE".localised() }
    // MARK: PROFILE CERTIFICATE
    static var CERTIFICATE: String { return "CERTIFICATE".localised() }
    static var CERTIFICATE_INFO: String { return "CERTIFICATE_INFO".localised()  }
    static var CERTIFICATE_SELECT_INFO: String { return "CERTIFICATE_SELECT_INFO".localised()  }
    static var CERTIFICATE_TAKE_PICTURE: String { return "CERTIFICATE_TAKE_PICTURE".localised()  }
    static var CERTIFICATE_UPLOAD_PICTURE: String { return "CERTIFICATE_UPLOAD_PICTURE".localised()  }
    static var OPTIONAL_CERTIFICATES: String { return "OPTIONAL_CERTIFICATES".localised() }
    static var ADD_ADDITIONAL_CERTIFICATES: String { return "ADD_ADDITIONAL_CERTIFICATES".localised() }
    // MARK: PROFILE ACCESS
    static var ACCESS_WITH_PIN: String { return "ACCESS_WITH_PIN".localised() }
    static var ENTER_NEW_PIN_TO_ACCESS: String { return "ENTER_NEW_PIN_TO_ACCESS".localised() }
    static var ACCESS_INFO: String { return "ACCESS_INFO".localised()  }
    static var PLEASE_REENTER_TO_VERIFY: String { return "PLEASE_REENTER_TO_VERIFY".localised()  }
    static var YOUR_PIN_IS_CORRECTLY_SET: String { return "YOUR_PIN_IS_CORRECTLY_SET".localised()  }
    static var CHANGE_PIN: String { return "CHANGE_PIN".localised()  }
    static var PLEASE_INSERT_YOUR_NEW_PIN: String { return "PLEASE_INSERT_YOUR_NEW_PIN".localised()  }
    static var WRONG_PIN: String { return "WRONG_PIN".localised()  }
    static var PLEASE_REENTER_YOUR_NEW_PIN_TO_VERIFY: String { return "PLEASE_REENTER_YOUR_NEW_PIN_TO_VERIFY".localised()  }
    static var INSERT_YOUR_CURRENT_PIN: String { return "INSERT_YOUR_CURRENT_PIN".localised()  }
    // MARK: PROFILE PERSONAL DATA
    static var PROFILE_INFO_FIRST_PAGE: String { return "PROFILE_INFO_FIRST_PAGE".localised()  }
    static var PROFILE_INFO_SECOND_PAGE: String { return "PROFILE_INFO_SECOND_PAGE".localised()  }
    static var PROFILE_INFO_THIRD_PAGE: String { return "PROFILE_INFO_THIRD_PAGE".localised()  }
    static var PROFILE_SUCCESS_TITLE: String { return "PROFILE_SUCCESS_TITLE".localised()  }
    static var PROFILE_SUCCESS_DESCRIPTION: String { return "PROFILE_SUCCESS_DESCRIPTION".localised()  }
    static var PROFILE_SUCCESS_DETAIL: String { return "PROFILE_SUCCESS_DETAIL".localised()  }
    static var PERSONAL_INFORMATION: String { return "PERSONAL_INFORMATION".localised()  }
    static var NAME: String { return "NAME".localised()  }
    static var EXAMPLE_NAME: String { return "EXAMPLE_NAME".localised()  }
    static var SURNAME: String { return "SURNAME".localised()  }
    static var EXAMPLE_SURNAME: String { return "EXAMPLE_SURNAME".localised()  }
    static var BIRTHDAY: String { return "BIRTHDAY".localised()  }
    static var EXAMPLE_DATE: String { return "EXAMPLE_DATE".localised()  }
    static var PHONE: String { return "PHONE".localised()  }
    static var EXAMPLE_PHONE_CODE: String { return "EXAMPLE_PHONE_CODE".localised()  }
    static var EXAMPLE_PHONE_NUMBER: String { return "EXAMPLE_PHONE_NUMBER".localised()  }
    static var ADDRESS: String { return "ADDRESS".localised()  }
    static var STREET: String { return "STREET".localised()  }
    static var EXAMPLE_STREET: String { return "EXAMPLE_STREET".localised()  }
    static var NUMBER: String { return "NUMBER".localised()  }
    static var EXAMPLE_NUMBER: String { return "EXAMPLE_NUMBER".localised()  }
    static var POSTAL_CODE: String { return "POSTAL_CODE".localised()  }
    static var EXAMPLE_POSTAL_CODE: String { return "EXAMPLE_POSTAL_CODE".localised()  }
    static var CITY: String { return "CITY".localised()  }
    static var EXAMPLE_CITY: String { return "EXAMPLE_CITY".localised()  }
    static var COUNTRY: String { return "COUNTRY".localised()  }
    static var EXAMPLE_COUNTRY: String { return "EXAMPLE_COUNTRY".localised()  }
    static var QUALIFICATION: String { return "QUALIFICATION".localised()  }
    static var MY_QUALIFICATION_FOR_REANIMATION: String { return "MY_QUALIFICATION_FOR_REANIMATION".localised()  }
    static var SELECT_ONE_OF_THE_OPTIONS_FROM_THE_LIST: String { return "SELECT_ONE_OF_THE_OPTIONS_FROM_THE_LIST".localised()  }
    static var MY_JOB: String { return "MY_JOB".localised()  }
    static var SEND_INFORMATION: String { return "SEND_INFORMATION".localised()  }
    // MARK: SETTINGS
    static var CHANGE_TONE: String { return "CHANGE_TONE".localised() }
    static var SELECT_ONE_OF_THE_TONES_FROM_THE_LIST: String { return "SELECT_ONE_OF_THE_TONES_FROM_THE_LIST".localised() }
    static var RECEIVE_TEST_ALARM_ON_SATURDAY: String { return "RECEIVE_TEST_ALARM_ON_SATURDAY".localised() }
    static var LOG_OUT: String { return "LOG_OUT".localised() }
    static var DELETE_ACCOUNT: String { return "DELETE_ACCOUNT".localised() }
    static var NOT_SPECIFIED: String { return "NOT_SPECIFIED".localised() }
    // MARK: STANDBY PAGE
    static var STANDBY_INFO: String { return "STANDBY_INFO".localised()  }
    static var STANDBY_DUTY_TIME_INFO: String { return "STANDBY_DUTY_TIME_INFO".localised()  }
    static var STANDBY_OPTIONS: String { return "STANDBY_OPTIONS".localised()  }
    static var DUTY_TIME: String { return "DUTY_TIME".localised()  }
    static var SELECT_THE_TIME: String { return "SELECT_THE_TIME".localised()  }
    static var FROM: String { return "FROM".localised()  }
    static var TO: String { return "TO".localised()  }
    static var SELECT_THE_DAYS_YOU_ARE_AVAILABLE: String { return "SELECT_THE_DAYS_YOU_ARE_AVAILABLE".localised()  }
    static var HOME: String { return "HOME".localised()  }
    static var HOME_STANDBY_INFO: String { return "HOME_STANDBY_INFO".localised()  }
    static var SAVE: String { return "SAVE".localised()  }
    // MARK: SOS PAGE
    static var EMERGENCY_CALL: String { return "EMERGENCY_CALL".localised()  }
    static var YOUR_CURRENT_POSITION: String { return "YOUR_CURRENT_POSITION".localised()  }
    static var GEO_LOCATION: String { return "GEO_LOCATION".localised()  }
    static var GO_BACK: String { return "GO_BACK".localised()  }
    // MARK: EVENTS PAGE
    static var CONTINUE_READING: String { return "CONTINUE_READING".localised() }
    static var DATE: String { return "DATE".localised() }
    static var COMPANY: String { return "COMPANY".localised() }
    // MARK: MAP
    static var DEFIBRILLATORS: String { return "DEFIBRILLATORS".localised() }
    static var YOUR_ADDED_DEFIBRILLATORS: String { return "YOUR_ADDED_DEFIBRILLATORS".localised() }
    static var ADD_NEW_DEFIBRILLATOR: String { return "ADD_NEW_DEFIBRILLATOR".localised() }
    static var SAVE_DEFIBRILLATOR: String { return "SAVE_DEFIBRILLATOR".localised() }
    static var UPDATE_DEFIBRILLATOR: String { return "UPDATE_DEFIBRILLATOR".localised() }
    static var OBJECT_TITLE: String { return "OBJECT_TITLE".localised() }
    static var OBJECT_TITLE_EXAMPLE: String { return "OBJECT_TITLE_EXAMPLE".localised() }
    static var AED_MANUFACTURER: String { return "AED_MANUFACTURER".localised() }
    static var AED_MODEL: String { return "AED_MODEL".localised() }
    static var AED_TYPE: String { return "AED_TYPE".localised() }
    static var AED_MODEL_EXAMPLE: String { return "AED_MODEL_EXAMPLE".localised() }
    static var AED_TYPE_EXAMPLE: String { return "AED_TYPE_EXAMPLE".localised() }
    static var COMMENTS: String { return "COMMENTS".localised() }
    static var IMAGES: String { return "IMAGES".localised() }
    static var ADD_ADDRESS: String { return "ADD_ADDRESS".localised() }
    static var LONG_PRESS_MAP_INFO: String { return "LONG_PRESS_MAP_INFO".localised() }
    static var FILTER_ANNOTATIONS: String { return "FILTER_ANNOTATIONS".localised() }
    // MARK: LOGIN-REGISTER
    static var LOGIN: String { return "LOGIN".localised() }
    static var EMAIL: String { return "EMAIL".localised() }
    static var PASSWORD: String { return "PASSWORD".localised() }
    static var DID_YOU_FORGET_YOUR_PASSWORD: String { return "DID_YOU_FORGET_YOUR_PASSWORD".localised() }
    static var ENTER_WITHOUT_REGISTRATION: String { return "ENTER_WITHOUT_REGISTRATION".localised() }
    static var PRESS_HERE: String { return "PRESS_HERE".localised() }
    static var EMAIL_NOT_VERIFIED: String { return "EMAIL_NOT_VERIFIED".localised() }
    static var PLEASE_CHECK_YOUR_INBOX: String { return "PLEASE_CHECK_YOUR_INBOX".localised() }
    static var EMAIL_OR_PASSWORD_WRONG: String { return "EMAIL_OR_PASSWORD_WRONG".localised() }
    static var PLEASE_CHECK_YOUR_INPUT: String { return "PLEASE_CHECK_YOUR_INPUT".localised() }
    static var NO_CONENCTION: String { return "NO_CONENCTION".localised() }
    static var PLEASE_CHECK_YOUR_CONNECTION_AND_TRY_AGAIN: String { return "PLEASE_CHECK_YOUR_CONNECTION_AND_TRY_AGAIN".localised() }
    static var AN_EMAIL_HAS_BEEN_SENT: String { return "AN_EMAIL_HAS_BEEN_SENT".localised() }
    static var EMAIL_ADDRESS_DOES_NOT_EXIST: String { return "EMAIL_ADDRESS_DOES_NOT_EXIST".localised() }
    static var PLEASE_CHECK_THE_ADDRESS: String { return "PLEASE_CHECK_THE_ADDRESS".localised() }
    static var PLEASE_TRY_AGAIN_LATER: String { return "PLEASE_TRY_AGAIN_LATER".localised() }
    static var EMAIL_COULDN_T_SEND: String { return "EMAIL_COULDN_T_SEND".localised() }
    static var PLEASE_PROVIDE_AN_EMAIL: String { return "PLEASE_PROVIDE_AN_EMAIL".localised() }
    static var REPEAT_PASSWORD: String { return "REPEAT_PASSWORD".localised() }
    static var PASSWORD_DETAIL: String { return "PASSWORD_DETAIL".localised() }
    static var EMAIL_ALREADY_IN_USE: String { return "EMAIL_ALREADY_IN_USE".localised() }
    static var PLEASE_USE_ANOTHER_EMAIL_ADDRESS: String { return "PLEASE_USE_ANOTHER_EMAIL_ADDRESS".localised() }
    static var ERROR: String { return "ERROR".localised() }
    static var INVALID_EMAIL_X: String { return "INVALID_EMAIL_X".localised() }
    static var PASSWORDS_DO_NOT_MATCH: String { return "PASSWORDS_DO_NOT_MATCH".localised() }
    static var REGISTRATION_SUCCESSFULLY_FINISHED: String { return "REGISTRATION_SUCCESSFULLY_FINISHED".localised() }
    static var EMAIL_VERIFICATION: String { return "EMAIL_VERIFICATION".localised() }
    static var EMAIL_VERIFICATION_DETAIL: String { return "EMAIL_VERIFICATION_DETAIL".localised() }
    static var VERIFY: String { return "VERIFY".localised() }
    static var SKIP: String { return "SKIP".localised() }
    static var FINISH: String { return "FINISH".localised() }
    static var CONGRATULATIONS: String { return "CONGRATULATIONS".localised() }
    static var YOU_ARE_A_FIRST_RESPONDER_NOW: String { return "YOU_ARE_A_FIRST_RESPONDER_NOW".localised() }
    static var REGISTER_SUCCESS_TITLE: String { return "REGISTER_SUCCESS_TITLE".localised() }
    static var REGISTER_SUCCESS_DESCRIPTION: String { return "REGISTER_SUCCESS_DESCRIPTION".localised() }
    // MARK: EMERGENCY
    static var FIRST_RESPONDER: String { return "FIRST_RESPONDER".localised() }
    static var JOB: String { return "JOB".localised() }
    static var PROFILE_ID: String { return "PROFILE_ID".localised() }
    static var EMERGENCY_NUMBER: String { return "EMERGENCY_NUMBER".localised() }
    static var CONTROL_CENTER: String { return "CONTROL_CENTER".localised() }
    static var EMERGENCY_NAME: String { return "EMERGENCY_NAME".localised() }
    static var ARE_YOU_READY_TO_ANSWER_THE_CALL: String { return "ARE_YOU_READY_TO_ANSWER_THE_CALL".localised() }
    static var TAKE_EMERGENCY: String { return "TAKE_EMERGENCY".localised() }
    static var INSERT_YOUR_PIN_TO_ACCEPT_EMERGENCY_CALL: String { return "INSERT_YOUR_PIN_TO_ACCEPT_EMERGENCY_CALL".localised() }
    static var PLEASE_AUTHENTICATE_WITH_YOUR_FINGERPRINT: String { return "PLEASE_AUTHENTICATE_WITH_YOUR_FINGERPRINT".localised() }
    static var NOT_AVAILABLE: String { return "NOT_AVAILABLE".localised() }
    static var GO: String { return "GO".localised() }
    static var BACK: String { return "BACK".localised() }
    static var FINISH_EMERGENCY: String { return "FINISH_EMERGENCY".localised() }
    static var CANCEL_EMERGENCY: String { return "CANCEL_EMERGENCY".localised() }
    static var PATIENT_REACHED: String { return "PATIENT_REACHED".localised() }
    static var FINISH_EMERGENCY_REASON: String { return "FINISH_EMERGENCY_REASON".localised() }
    static var DISTANCE: String { return "DISTANCE".localised() }
    static var DESCRIPTION: String { return "DESCRIPTION".localised() }
    static var OBJECT: String { return "OBJECT".localised() }
    static var PATIENT: String { return "PATIENT".localised() }
    static var INDICATOR: String { return "INDICATOR".localised() }
    static var GEO_COORDINATION: String { return "GEO_COORDINATION".localised() }
    static var KEYWORD: String { return "KEYWORD".localised() }
    static var PATIENT_REPORT: String { return "PATIENT_REPORT".localised() }
    static var EMERGENCY_FINAL_TITLE: String { return "EMERGENCY_FINAL_TITLE".localised() }
    static var EMERGENCY_FINAL_DESCRIPTION: String { return "EMERGENCY_FINAL_DESCRIPTION".localised() }
    static var FILL_REPORT: String { return "FILL_REPORT".localised() }
    static var FILL_REPORT_LATER: String { return "FILL_REPORT_LATER".localised() }
    // MARK: PROTOCOLS
    static var PATIENT_REPORT_PROTOCOLS: String { return "PATIENT_REPORT_PROTOCOLS".localised() }
    static var REPORT_SAVE_ALERT: String { return "REPORT_SAVE_ALERT".localised() }
    static var CONTINUE_FILLING_REPORT: String { return "CONTINUE_FILLING_REPORT".localised() }
    static var GO_TO_HOME_PAGE: String { return "GO_TO_HOME_PAGE".localised() }
    static var REPORT_SUCCESS_TITLE: String { return "REPORT_SUCCESS_TITLE".localised() }
    static var REPORT_SUCCESS_DESCRIPTION: String { return "REPORT_SUCCESS_DESCRIPTION".localised() }
    static var ARRIVAL_TIME_TITLE: String { return "ARRIVAL_TIME_TITLE".localised() }
    static var ARRIVAL_TIME_SUBTITLE: String { return "ARRIVAL_TIME_SUBTITLE".localised() }
    static var ARRIVED_AT_SUBTITLE: String { return "ARRIVED_AT_SUBTITLE".localised() }
    static var DURATION_UNIT_MIN: String { return "DURATION_UNIT_MIN".localised() }
    static var AGE_CATEGORY_TITLE: String { return "AGE_CATEGORY_TITLE".localised() }
    static var AGE_CATEGORY_SUBTITLE: String { return "AGE_CATEGORY_SUBTITLE".localised() }
    static var SEX_CATEGORY_TITLE: String { return "SEX_CATEGORY_TITLE".localised() }
    static var SEX_CATEGORY_SUBTITLE: String { return "SEX_CATEGORY_SUBTITLE".localised() }
    static var RESUSCITATION_TITLE: String { return "RESUSCITATION_TITLE".localised() }
    static var RESUSCITATION_SUBTITLE: String { return "RESUSCITATION_SUBTITLE".localised() }
    static var LOCATION_TITLE: String { return "LOCATION_TITLE".localised() }
    static var LOCATION_SUBTITLE: String { return "LOCATION_SUBTITLE".localised() }
    static var SCHOOLBUILDING_TITLE: String { return "SCHOOLBUILDING_TITLE".localised() }
    static var SCHOOLBUILDING_SUBTITLE: String { return "SCHOOLBUILDING_SUBTITLE".localised() }
    static var START_DIAGNOSIS_TITLE: String { return "START_DIAGNOSIS_TITLE".localised() }
    static var START_DIAGNOSIS_SUBTITLE: String { return "START_DIAGNOSIS_SUBTITLE".localised() }
    static var START_ORIENTATION_TITLE: String { return "START_ORIENTATION_TITLE".localised() }
    static var START_ORIENTATION_SUBTITLE: String { return "START_ORIENTATION_SUBTITLE".localised() }
    static var CONSCIOUSNESS_TITLE: String { return "CONSCIOUSNESS_TITLE".localised() }
    static var CONSCIOUSNESS_SUBTITLE: String { return "CONSCIOUSNESS_SUBTITLE".localised() }
    static var START_BREATHING_TITLE: String { return "START_BREATHING_TITLE".localised() }
    static var START_BREATHING_SUBTITLE: String { return "START_BREATHING_SUBTITLE".localised() }
    static var SPORTS_RELATION_TITLE: String { return "SPORTS_RELATION_TITLE".localised() }
    static var SPORTS_RELATION_SUBTITLE: String { return "SPORTS_RELATION_SUBTITLE".localised() }
    static var COLLAPSE_OBSERVED_TITLE: String { return "COLLAPSE_OBSERVED_TITLE".localised() }
    static var COLLAPSE_OBSERVED_SUBTITLE: String { return "COLLAPSE_OBSERVED_SUBTITLE".localised() }
    static var CARDIAC_MASSAGE_TITLE: String { return "CARDIAC_MASSAGE_TITLE".localised() }
    static var CARDIAC_MASSAGE_SUBTITLE: String { return "CARDIAC_MASSAGE_SUBTITLE".localised() }
    static var VENTILATION_TITLE: String { return "VENTILATION_TITLE".localised() }
    static var VENTILATION_SUBTITLE: String { return "VENTILATION_SUBTITLE".localised() }
    static var TELEMEDICINE_TITLE: String { return "TELEMEDICINE_TITLE".localised() }
    static var TELEMEDICINE_SUBTITLE: String { return "TELEMEDICINE_SUBTITLE".localised() }
    static var DEFI_TITLE: String { return "DEFI_TITLE".localised() }
    static var DEFI_SUBTITLE: String { return "DEFI_SUBTITLE".localised() }
    static var DEFI2_TITLE: String { return "DEFI2_TITLE".localised() }
    static var DEFI2_SUBTITLE: String { return "DEFI2_SUBTITLE".localised() }
    static var DEFI3_SUBTITLE: String { return "DEFI3_SUBTITLE".localised() }
    static var DEFI4_TITLE: String { return "DEFI4_TITLE".localised() }
    static var DEFI4_SUBTITLE: String { return "DEFI4_SUBTITLE".localised() }
    static var END_CONSCIOUSNESS_TITLE: String { return "END_CONSCIOUSNESS_TITLE".localised() }
    static var END_CONSCIOUSNESS_SUBTITLE: String { return "END_CONSCIOUSNESS_SUBTITLE".localised() }
    static var END_BREATHING_TITLE: String { return "END_BREATHING_TITLE".localised() }
    static var END_BREATHING_SUBTITLE: String { return "END_BREATHING_SUBTITLE".localised() }
    static var END_REMARKS_TITLE: String { return "END_REMARKS_TITLE".localised() }
    static var END_REMARKS_SUBTITLE: String { return "END_REMARKS_SUBTITLE".localised() }
    static var SAVE_REPORT_AND_SEND: String { return "SAVE_REPORT_AND_SEND".localised() }
    static var DONE: String { return "DONE".localised() }
    static var CANCELLED_REPORT_REMARKS_TITLE: String { return "CANCELLED_REPORT_REMARKS_TITLE".localised() }
    // MARK: REPORT DATA
    static var APARTMENT: String { return "APARTMENT".localised() }
    static var RETIREMENT_HOME: String { return "RETIREMENT_HOME".localised() }
    static var OFFICE: String { return "OFFICE".localised() }
    static var DOCTOR_S_OFFICE: String { return "DOCTOR_S_OFFICE".localised() }
    static var LOCATION_STREET: String { return "LOCATION_STREET".localised() }
    static var PUBLIC: String { return "PUBLIC".localised() }
    static var HOSPITAL: String { return "HOSPITAL".localised() }
    static var MASS_EVENT: String { return "MASS_EVENT".localised() }
    static var OTHER: String { return "OTHER".localised() }
    static var EDUCATIONAL_INSTITUTION: String { return "EDUCATIONAL_INSTITUTION".localised() }
    static var SPORTS_CLUB: String { return "SPORTS_CLUB".localised() }
    static var BIRTH_HOUSE: String { return "BIRTH_HOUSE".localised() }
    static var UNKNOWN: String { return "UNKNOWN".localised() }
    static var CARDIAL: String { return "CARDIAL".localised() }
    static var TRAUMA: String { return "TRAUMA".localised() }
    static var DROWNING: String { return "DROWNING".localised() }
    static var HYPOXIA: String { return "HYPOXIA".localised() }
    static var INTOXICATION: String { return "INTOXICATION".localised() }
    static var ICB_SAB: String { return "ICB_SAB".localised() }
    static var SIDS: String { return "SIDS".localised() }
    static var BLEED_TO_DEATH: String { return "BLEED_TO_DEATH".localised() }
    static var STROKE: String { return "STROKE".localised() }
    static var METABOLIC: String { return "METABOLIC".localised() }
    static var OTHERS: String { return "OTHERS".localised() }
    static var SEPSIS: String { return "SEPSIS".localised() }
    static var NOT_DOCUMENTED: String { return "NOT_DOCUMENTED".localised() }
    static var NARCOTIZED: String { return "NARCOTIZED".localised() }
    static var AWAKE: String { return "AWAKE".localised() }
    static var RESPONDS_TO_SPEECH: String { return "RESPONDS_TO_SPEECH".localised() }
    static var RESPONDS_TO_PAIN: String { return "RESPONDS_TO_PAIN".localised() }
    static var UNCONSCIOUS: String { return "UNCONSCIOUS".localised() }
    static var DEATH: String { return "DEATH".localised() }
    static var SLEEPY: String { return "SLEEPY".localised() }
    static var NOT_ASSESSABLE: String { return "NOT_ASSESSABLE".localised() }
    static var NORMAL: String { return "NORMAL".localised() }
    static var LIMITED_ORIENTED: String { return "LIMITED_ORIENTED".localised() }
    static var DISORIENTED: String { return "DISORIENTED".localised() }
    static var DILATED: String { return "DILATED".localised() }
    static var MID_DILATED: String { return "MID_DILATED".localised() }
    static var NARROW: String { return "NARROW".localised() }
    static var GASPING: String { return "GASPING".localised() }
    static var APNEA: String { return "APNEA".localised() }
    static var RESPIRATION: String { return "RESPIRATION".localised() }
    static var NORMAL_BREATHING: String { return "NORMAL_BREATHING".localised() }
    static var RECOVERY_POSITION: String { return "RECOVERY_POSITION".localised() }
    static var FEET_ELEVATED: String { return "FEET_ELEVATED".localised() }
    static var HEAD_ELEVATED: String { return "HEAD_ELEVATED".localised() }
    static var CREATED_FREE_AIRWAYS: String { return "CREATED_FREE_AIRWAYS".localised() }
    static var ACCIDENTALLY_PRESENT_WITNESS: String { return "ACCIDENTALLY_PRESENT_WITNESS".localised() }
    static var APP_FIRST_RESPONDER: String { return "APP_FIRST_RESPONDER".localised() }
    static var NOT_OBSERVED: String { return "NOT_OBSERVED".localised() }
    static var WAS_NOT_CARRIED_OUT: String { return "WAS_NOT_CARRIED_OUT".localised() }
    static var NOT_SPECIFIED_PATIENT_NOT_REANIMATED: String { return "NOT_SPECIFIED_PATIENT_NOT_REANIMATED".localised() }
    static var RUNNING_REANIMATION: String { return "RUNNING_REANIMATION".localised() }
    static var PATIENT_IS_CONSCIOUS: String { return "PATIENT_IS_CONSCIOUS".localised() }
    static var PATIENT_DECEASED: String { return "PATIENT_DECEASED".localised() }
    static var LATER_THAN_AMBULANCE: String { return "LATER_THAN_AMBULANCE".localised() }
    static var EARLIER_THAN_AMBULANCE: String { return "EARLIER_THAN_AMBULANCE".localised() }
    static var MONOPHASIC: String { return "MONOPHASIC".localised() }
    static var BINOPHASIC: String { return "BINOPHASIC".localised() }
    static var X_DAYS: String { return "X_DAYS".localised() }
    static var YOUNGER_THAN_X_YEAR: String { return "YOUNGER_THAN_X_YEAR".localised() }
    static var SPECIFY_APPROXIMATE_AGE: String { return "SPECIFY_APPROXIMATE_AGE".localised() }
    static var MALE: String { return "MALE".localised() }
    static var FEMALE: String { return "FEMALE".localised() }
    static var REANIMATION_01: String { return "REANIMATION_01".localised() }
    static var REANIMATION_02: String { return "REANIMATION_02".localised() }
    static var REANIMATION_03: String { return "REANIMATION_03".localised() }
    static var REANIMATION_04: String { return "REANIMATION_04".localised() }
    static var NO: String { return "NO".localised() }
    static var YES: String { return "YES".localised() }
    static var SHOCK: String { return "SHOCK".localised() }
    static var MORE_THAN: String { return "MORE_THAN".localised() }
    static var LAERDAL_PHILLIPS_HP: String { return "LAERDAL_PHILLIPS_HP".localised() }
    static var SCHILLER_BRUKER: String { return "SCHILLER_BRUKER".localised() }
    static var GS_ELEKTROMEDIZINISCHE_GERAETE: String { return "GS_ELEKTROMEDIZINISCHE_GERAETE".localised() }
    static var MEDTRONIC_PHYSIO_CONTROL: String { return "MEDTRONIC_PHYSIO_CONTROL".localised() }
    static var MARQUETTE: String { return "MARQUETTE".localised() }
    static var ZOLL: String { return "ZOLL".localised() }
    static var PRIMEDIC: String { return "PRIMEDIC".localised() }
    static var DRAEGER: String { return "DRAEGER".localised() }
    static var WEINMANN: String { return "WEINMANN".localised() }
    static var WELCH_ALLYN: String { return "WELCH_ALLYN".localised() }
    static var GE: String { return "GE".localised() }
    static var DEFIBTECH: String { return "DEFIBTECH".localised() }
    static var CU_MEDICAL_SYSTEMS: String { return "CU_MEDICAL_SYSTEMS".localised() }
    static var HEARTSINE: String { return "HEARTSINE".localised() }
    static var UNCLASSIFIED: String { return "UNCLASSIFIED".localised() }
    static var PRIVATE_AED: String { return "PRIVATE_AED".localised() }
    static var PUBLIC_AED: String { return "PUBLIC_AED".localised() }
    // MARK: USER DATA
    static var DOCTOR_WITHOUT_SPECIALIZATION: String { return "DOCTOR_WITHOUT_SPECIALIZATION".localised() }
    static var INTENSIVE_CARE_NURSE: String { return "INTENSIVE_CARE_NURSE".localised() }
    static var GENERAL_NURSE: String { return "GENERAL_NURSE".localised() }
    static var EMERGENCY_DOCTOR: String { return "EMERGENCY_DOCTOR".localised() }
    static var DOCTOR_S_ASSISTANT: String { return "DOCTOR_S_ASSISTANT".localised() }
    static var VOLUNTEER_FIRE_DEPARTMENT: String { return "VOLUNTEER_FIRE_DEPARTMENT".localised() }
    static var THW: String { return "THW".localised() }
    static var DENTIST: String { return "DENTIST".localised() }
    static var POLICE: String { return "POLICE".localised() }
    static var NURSE: String { return "NURSE".localised() }
    static var EMERGENCY_PARAMEDIC: String { return "EMERGENCY_PARAMEDIC".localised() }
    static var FIRE_CHIEF: String { return "FIRE_CHIEF".localised() }
    static var RESCUE_ASSISTANT: String { return "RESCUE_ASSISTANT".localised() }
    static var PARAMEDIC: String { return "PARAMEDIC".localised() }
    static var RESCUE_WORKER: String { return "RESCUE_WORKER".localised() }
    static var MEDICAL_STUDENT: String { return "MEDICAL_STUDENT".localised() }
    static var STUDENT_AND_OTHER: String { return "STUDENT_AND_OTHER".localised() }
    static var DOCTOR: String { return "DOCTOR".localised() }
    static var FIRE_DEPARTMENT_PRO: String { return "FIRE_DEPARTMENT_PRO".localised() }
    static var FIRE_DEPARTMENT_VOLUNTARY: String { return "FIRE_DEPARTMENT_VOLUNTARY".localised() }
    static var AID_ORGANIZATION: String { return "AID_ORGANIZATION".localised() }
    static var THERAPIST: String { return "THERAPIST".localised() }
    static var ARMY: String { return "ARMY".localised() }
    static var STUDENT: String { return "STUDENT".localised() }
    static var BLS_COURSE: String { return "BLS_COURSE".localised() }
    static var FA_COURSE: String { return "FA_COURSE".localised() }
    static var DOCTOR_WITH_SUBSPECIALTY_EMERGENCY_MEDICINE: String { return "DOCTOR_WITH_SUBSPECIALTY_EMERGENCY_MEDICINE".localised() }
    static var PARAMEDIC_TRAINING: String { return "PARAMEDIC_TRAINING".localised() }
    // MARK: OTHERS
    static var MONDAY: String { return "MONDAY".localised() }
    static var TUESDAY: String { return "TUESDAY".localised() }
    static var WEDNESDAY: String { return "WEDNESDAY".localised() }
    static var THURSDAY: String { return "THURSDAY".localised() }
    static var FRIDAY: String { return "FRIDAY".localised() }
    static var SATURDAY: String { return "SATURDAY".localised() }
    static var SUNDAY: String { return "SUNDAY".localised() }
    static var DEFIBRILLATOR: String { return "DEFIBRILLATOR".localised() }
    static var FIRE_DEPARTMENT: String { return "FIRE_DEPARTMENT".localised() }
    static var PHARMACY: String { return "PHARMACY".localised() }
    static var ZIP: String { return "ZIP".localised() }
    static var NUMBER_SHORT: String { return "NUMBER_SHORT".localised() }
    static var IMPRINT_COULD_NOT_BE_LOADED: String { return "IMPRINT_COULD_NOT_BE_LOADED".localised() }
    static var IMPRINT_IS_LOADING: String { return "IMPRINT_IS_LOADING".localised() }
    static var LEGAL_NOTICES_COULD_NOT_BE_LOADED: String { return "LEGAL_NOTICES_COULD_NOT_BE_LOADED".localised() }
    static var LEGAL_NOTICES_ARE_LOADING: String { return "LEGAL_NOTICES_ARE_LOADING".localised() }
    static var OK: String { return "OK".localised() }
    static var CURRENTLY_NO_EVENT: String { return "CURRENTLY_NO_EVENT".localised() }
    static var EXPIRED: String { return "EXPIRED".localised() }
    static var LOCALIZATION_ERROR: String { return "LOCALIZATION_ERROR".localised() }
    static var LOCATION_ERROR_DETAIL: String { return "LOCATION_ERROR_DETAIL".localised() }
    static var ADDRESS_IS_MISSING: String { return "ADDRESS_IS_MISSING".localised() }
    static var OBJECT_CITY_POSTAL_CODE_MUST_BE_SPECIFIED: String { return "OBJECT_CITY_POSTAL_CODE_MUST_BE_SPECIFIED".localised() }
    static var ADDRESS_OF_THE_DEFIBRILLATOR_DESCRIPTION_AED_MANUFACTURER_MUST_BE_SPECIFIED: String { return "ADDRESS_OF_THE_DEFIBRILLATOR_DESCRIPTION_AED_MANUFACTURER_MUST_BE_SPECIFIED".localised() }
    static var PLEASE_WAIT: String { return "PLEASE_WAIT".localised() }
    static var DEFIBRILLATOR_IS_SAVED: String { return "DEFIBRILLATOR_IS_SAVED".localised() }
    static var DEFIBRILLATOR_COULD_NOT_BE_SAVED: String { return "DEFIBRILLATOR_COULD_NOT_BE_SAVED".localised() }
    static var THANKS_FOR_YOUR_HELP: String { return "THANKS_FOR_YOUR_HELP".localised() }
    static var CANCEL: String { return "CANCEL".localised() }
    static var TAKE_A_PHOTO: String { return "TAKE_A_PHOTO".localised() }
    static var OPEN_MEDIA_CENTER: String { return "OPEN_MEDIA_CENTER".localised() }
    static var HORN: String { return "HORN".localised() }
    static var SIREN: String { return "SIREN".localised() }
    static var ALARM: String { return "ALARM".localised() }
    static var URL: String { return "URL".localised() }
    static var NAVIGATE_WITH_APPLE_MAPS: String { return "NAVIGATE_WITH_APPLE_MAPS".localised() }
    static var NOTE: String { return "NOTE".localised() }
    static var NO_INFORMATION: String { return "NO_INFORMATION".localised() }
    static var ROUTE_IS_CALCULATED: String { return "ROUTE_IS_CALCULATED".localised() }
    static var X_MIN_TO_WALK: String { return "X_MIN_TO_WALK".localised() }
    static var ROUTE_UNKNOWN: String { return "ROUTE_UNKNOWN".localised() }
    static var FROM_X_TO_Y: String { return "FROM_X_TO_Y".localised() }
    static var SERVICE_REQUESTED: String { return "SERVICE_REQUESTED".localised() }
    static var YOU_ACCEPTED: String { return "YOU_ACCEPTED".localised() }
    static var YOU_CANCELLED: String { return "YOU_CANCELLED".localised() }
    static var YOU_FINISHED: String { return "YOU_FINISHED".localised() }
    static var EMERGENCY_UNIT_CANCELLED_THE_MISSION: String { return "EMERGENCY_UNIT_CANCELLED_THE_MISSION".localised() }
    static var ACCEPTED: String { return "ACCEPTED".localised() }
    static var CANCELLED: String { return "CANCELLED".localised() }
    static var FINISHED: String { return "FINISHED".localised() }
    static var PERMISSION_NOTIFICATION: String { return "PERMISSION_NOTIFICATION".localised() }
    static var PERMISSION_NOTIFICATION_DESCRIPTION: String { return "PERMISSION_NOTIFICATION_DESCRIPTION".localised() }
    static var OPEN_CONFIGURATION: String { return "OPEN_CONFIGURATION".localised() }
    static var PERMISSION_NOTIFICATION_NOT_ALLOWED: String { return "PERMISSION_NOTIFICATION_NOT_ALLOWED".localised() }
    static var ALLOW: String { return "ALLOW".localised() }
    static var PERMISSION_STAY_INFORMED: String { return "PERMISSION_STAY_INFORMED".localised() }
    static var PERMISSION_GET_ERMERGENCY_MISSION: String { return "PERMISSION_GET_ERMERGENCY_MISSION".localised() }
    static var DELETE: String { return "DELETE".localised() }
    static var OTHER_DOCUMENT: String { return "OTHER_DOCUMENT".localised() }
    static var DOCUMENT_REVIEW_INFO: String { return "DOCUMENT_REVIEW_INFO".localised() }
    static var DOCUMENT_REJECTED_INFO: String { return "DOCUMENT_REJECTED_INFO".localised() }
    static var NOT_UPLOADED: String { return "NOT_UPLOADED".localised() }
    static var IN_REVIEW: String { return "IN_REVIEW".localised() }
    static var VERIFIED: String { return "VERIFIED".localised() }
    static var REJECTED: String { return "REJECTED".localised() }
    static var AN_ERROR_HAS_OCCURED: String { return "AN_ERROR_HAS_OCCURED".localised() }
    static var PROOF_OF_QUALITY_IS_SAVING: String { return "PROOF_OF_QUALITY_IS_SAVING".localised() }
    static var PROOF_OF_QUALITY_IS_SAVED: String { return "PROOF_OF_QUALITY_IS_SAVED".localised() }
    static var SAVE_BASIS_AGREEMENT: String { return "SAVE_BASIS_AGREEMENT".localised() }
    static var BASIS_AGREEMENT_IS_SAVING: String { return "BASIS_AGREEMENT_IS_SAVING".localised() }
    static var BASIS_AGREEMENT_SAVED: String { return "BASIS_AGREEMENT_SAVED".localised() }
    static var LOAD_BASIS_AGREEMENT: String { return "LOAD_BASIS_AGREEMENT".localised() }
    static var BASIS_AGREEMENT_IS_LOADING: String { return "BASIS_AGREEMENT_IS_LOADING".localised() }
    static var AN_ERROR_OCCURED_WHILE_SAVING_THE_BASIS_AGREEMENT: String { return "AN_ERROR_OCCURED_WHILE_SAVING_THE_BASIS_AGREEMENT".localised() }
    static var YOUR_PROFILE_COULD_NOT_BE_UPDATED: String { return "YOUR_PROFILE_COULD_NOT_BE_UPDATED".localised() }
    static var MISSION_PROTOCOL: String { return "MISSION_PROTOCOL".localised() }
    static var THANK_YOU_FOR_UPLOADING_THE_EMERGENCY_REPORT: String { return "THANK_YOU_FOR_UPLOADING_THE_EMERGENCY_REPORT".localised() }
    static var MOBILE_AED_IS_SAVING: String { return "MOBILE_AED_IS_SAVING".localised() }
    static var MOBILE_AED_IS_SAVED: String { return "MOBILE_AED_IS_SAVED".localised() }
    static var MOBILE_AED_COULDN_T_SAVED: String { return "MOBILE_AED_COULDN_T_SAVED".localised() }
    static var PLEASE_FILL_IN_EVERYTHING: String { return "PLEASE_FILL_IN_EVERYTHING".localised() }
    static var CURRENTLY_NO_NEWS: String { return "CURRENTLY_NO_NEWS".localised() }
    static var EMERGENCY_NEARBY: String { return "EMERGENCY_NEARBY".localised() }
    static var RECEIVED_EMERGENCY_IS_EXPIRED: String { return "RECEIVED_EMERGENCY_IS_EXPIRED".localised() }
    static var YOU_ARE_ON_DUTY_AGAIN: String { return "YOU_ARE_ON_DUTY_AGAIN".localised() }
    static var EMERGENCY: String { return "EMERGENCY".localised() }
    static var FAQ_COULD_NOT_BE_LOADED: String { return "FAQ_COULD_NOT_BE_LOADED".localised() }
    static var FAQ_IS_LOADING: String { return "FAQ_IS_LOADING".localised() }
    static var PERMISSION_LOCATION: String { return "PERMISSION_LOCATION".localised() }
    static var PERMISSION_LOCATION_DESCRIPTION: String { return "PERMISSION_LOCATION_DESCRIPTION".localised() }
    static var PERMISSION_LOCATION_ALWAYS: String { return "PERMISSION_LOCATION_ALWAYS".localised() }
    static var PERMISSION_LOCATION_WHEN_IN_USE: String { return "PERMISSION_LOCATION_WHEN_IN_USE".localised() }
    static var PERMISSION_LOCATION_NEVER: String { return "PERMISSION_LOCATION_NEVER".localised() }
    static var PERMISSION_LOCATION_NEED_ACCESS_ALWAYS: String { return "PERMISSION_LOCATION_NEED_ACCESS_ALWAYS".localised() }
    static var PERMISSION_LOCATION_NEED_ACCESS: String { return "PERMISSION_LOCATION_NEED_ACCESS".localised() }
    static var PERMISSION_CAN_BE_RESET_IN_SETTINGS: String { return "PERMISSION_CAN_BE_RESET_IN_SETTINGS".localised() }
    static var PLEASE_WAIT_FOR_SOME_SECONDS: String { return "PLEASE_WAIT_FOR_SOME_SECONDS".localised() }
    static var SAVE_FAILED: String { return "SAVE_FAILED".localised() }
    static var TODAY: String { return "TODAY".localised() }
    static var USER_DEFIBRILLATOR_EMPTY_VIEW_SUBTITLE: String { return "USER_DEFIBRILLATOR_EMPTY_VIEW_SUBTITLE".localised() }
    static var AVAILABLE: String { return "AVAILABLE".localised() }
    static var DEFIBRILLATOR_IN_REVIEW: String { return "DEFIBRILLATOR_IN_REVIEW".localised() }
    static var VERIFIED_BY_ASB: String { return "VERIFIED_BY_ASB".localised() }
    static var IN_PROCESS: String { return "IN_PROCESS".localised() }
    static var SEARCHING_FOR_PLACES: String { return "SEARCHING_FOR_PLACES".localised() }
    static var ONLY_FOR_ACTIVE_FIRST_RESPONDERS: String { return "ONLY_FOR_ACTIVE_FIRST_RESPONDERS".localised() }
    static var PLEASE_LOGIN_IN_ORDER_TO_ADD_DEFIBRILLATORS: String { return "PLEASE_LOGIN_IN_ORDER_TO_ADD_DEFIBRILLATORS".localised() }
    static var PERMISSION_SEE_YOUR_LOCATION_IN_MAP: String { return "PERMISSION_SEE_YOUR_LOCATION_IN_MAP".localised() }
    static var PERMISSION_GET_IMPROVED_EXPERIENCE: String { return "PERMISSION_GET_IMPROVED_EXPERIENCE".localised() }
    static var MORE: String { return "MORE".localised() }
    static var NEXT: String { return "NEXT".localised() }
    static var RETAKE: String { return "RETAKE".localised() }
    static var TAKE_PICTURE_OF_YOUR_CERTIFICATE: String { return "TAKE_PICTURE_OF_YOUR_CERTIFICATE".localised() }
    static var PREVIEW_OF_THE_CERTIFICATE: String { return "PREVIEW_OF_THE_CERTIFICATE".localised() }
    static var SIGN_AGREEMENT: String { return "SIGN_AGREEMENT".localised() }
    static var ABOUT_THE_PROJECT: String { return "ABOUT_THE_PROJECT".localised() }
    static var ABOUT_THE_PROJECT_COULD_NOT_BE_LOADED: String { return "ABOUT_THE_PROJECT_COULD_NOT_BE_LOADED".localised() }
    static var ABOUT_THE_PROJECT_IS_LOADING: String { return "ABOUT_THE_PROJECT_IS_LOADING".localised() }
    static var STANDBY_SUCCESS_DESCRIPTION: String { return "STANDBY_SUCCESS_DESCRIPTION".localised() }
    static var ACCEPTED_AT: String { return "ACCEPTED_AT".localised() }
    static var ENDED_AT: String { return "ENDED_AT".localised() }
    static var ARRIVED_AT: String { return "ARRIVED_AT".localised() }
    static var EMERGENCY_CANCELLED: String { return "EMERGENCY_CANCELLED".localised() }
    static var EMERGENCY_CANCELLED_DETAIL: String { return "EMERGENCY_CANCELLED_DETAIL".localised() }
    static var MISSED_EMERGENCY_TITLE: String { return "MISSED_EMERGENCY_TITLE".localised() }
    static var MISSED_EMERGENCY_DETAIL: String { return "MISSED_EMERGENCY_DETAIL".localised() }
    static var MISSED_EMERGENCY_ADDRESS: String { return "MISSED_EMERGENCY_ADDRESS".localised() }
    static var MISSED_EMERGENCY_PROFILE_INCOMPLETE_TITLE: String { return "MISSED_EMERGENCY_PROFILE_INCOMPLETE_TITLE".localised() }
    static var MISSED_EMERGENCY_PROFILE_INCOMPLETE_DETAIL: String { return "MISSED_EMERGENCY_PROFILE_INCOMPLETE_DETAIL".localised() }
    static var DAY: String { return "DAY".localised() }
    static var HOUR: String { return "HOUR".localised() }
    static var MINUTE: String { return "MINUTE".localised() }
    static var DAYS: String { return "DAYS".localised() }
    static var HOURS: String { return "HOURS".localised() }
    static var MINUTES: String { return "MINUTES".localised() }
    static var CERTIFICATE_LEAVE_ALERT: String { return "CERTIFICATE_LEAVE_ALERT".localised() }
    static var LEAVE_THIS_PAGE: String { return "LEAVE_THIS_PAGE".localised() }
    static var DELETE_ACCOUNT_ALERT: String { return "DELETE_ACCOUNT_ALERT".localised() }
    static var TEST_EMERGENCY_BUTTON_TITLE: String { return "TEST_EMERGENCY_BUTTON_TITLE".localised() }
    static var CERTIFICATE_FINAL_DESCRIPTION: String { return "CERTIFICATE_FINAL_DESCRIPTION".localised() }
    static var TO_ADD_LOCATION_AUTOMATICALLY: String { return "TO_ADD_LOCATION_AUTOMATICALLY".localised() }
    // MARK: INTRO
    static var CONTINUE: String { return "CONTINUE".localised() }
    static var SKIP_INTRODUCTION: String { return "SKIP_INTRODUCTION".localised() }
    static var INTRO_FIRST_PAGE_TITLE: String { return "INTRO_FIRST_PAGE_TITLE".localised() }
    static var INTRO_FIRST_PAGE_DETAIL: String { return "INTRO_FIRST_PAGE_DETAIL".localised() }
    static var INTRO_SECOND_PAGE_TITLE: String { return "INTRO_SECOND_PAGE_TITLE".localised() }
    static var INTRO_SECOND_PAGE_DETAIL: String { return "INTRO_SECOND_PAGE_DETAIL".localised() }
    static var INTRO_THIRD_PAGE_TITLE: String { return "INTRO_THIRD_PAGE_TITLE".localised() }
    static var INTRO_THIRD_PAGE_DETAIL: String { return "INTRO_THIRD_PAGE_DETAIL".localised() }
    static var INTRO_FOURTH_PAGE_TITLE: String { return "INTRO_FOURTH_PAGE_TITLE".localised() }
    static var INTRO_FOURTH_PAGE_DETAIL: String { return "INTRO_FOURTH_PAGE_DETAIL".localised() }
    static var INTRO_FIFTH_PAGE_TITLE: String { return "INTRO_FIFTH_PAGE_TITLE".localised() }
    static var INTRO_FIFTH_PAGE_DETAIL: String { return "INTRO_FIFTH_PAGE_DETAIL".localised() }
    static var INTRO_SIXTH_PAGE_TITLE: String { return "INTRO_SIXTH_PAGE_TITLE".localised() }
    static var INTRO_SIXTH_PAGE_DETAIL: String { return "INTRO_SIXTH_PAGE_DETAIL".localised() }
    // MARK: OTHERS
    static var CRITICAL_ALERT: String { return "CRITICAL_ALERT".localised() }
    static var CRITICAL_ALERT_INFO: String { return "CRITICAL_ALERT_INFO".localised() }
    static var ENABLED: String { return "ENABLED".localised() }
    static var DISABLED: String { return "DISABLED".localised() }
    static var MOBILE_AED: String { return "MOBILE_AED".localised() }
    // MARK: EMERGENCY TASK
    static var TASK: String { return "TASK".localised() }
    static var FIRST_RESPONDER_TASK: String { return "FIRST_RESPONDER_TASK".localised() }
    static var GET_AED_TASK: String { return "GET_AED_TASK".localised() }
    static var FIRST_RESPONDER_TASK_INFO: String { return "FIRST_RESPONDER_TASK_INFO".localised() }
    static var GET_AED_TASK_INFO: String { return "GET_AED_TASK_INFO".localised() }
    static var TASK_ALERT_INFO: String { return "TASK_ALERT_INFO".localised() }
    // MARK: SUB CONTRACTS
    static var CONTRACT_LIST_INFO: String { return "CONTRACT_LIST_INFO".localised() }
    static var BASIC_AGREEMENT: String { return "BASIC_AGREEMENT".localised() }
    static var SUPPLEMENTARY_AGREEMENT: String { return "SUPPLEMENTARY_AGREEMENT".localised() }
}
